// @vitest-environment happy-dom
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { mount } from '@vue/test-utils'
import { afterEach, describe, expect, it } from 'vitest'
import ApiReferencePage from '../src/pages/ApiReferencePage.vue'
import docs from '../src/generated/component-api.json'

const root=resolve(import.meta.dirname,'..')
const manifest=JSON.parse(readFileSync(resolve(root,'api-manifest.json'),'utf8'))
const publicDocs=JSON.parse(readFileSync(resolve(root,'public/component-api.json'),'utf8'))
const markdown=readFileSync(resolve(root,'COMPONENT-API.md'),'utf8')
const mounted=[]
afterEach(()=>{while(mounted.length)mounted.pop().unmount();history.replaceState(null,'','/')})

describe('P37 generated component API documentation',()=>{
  it('publishes schema 3 signature and runtime default details for every component',()=>{
    expect(manifest.schemaVersion).toBe(3)
    expect(manifest.components).toHaveLength(89)
    for(const component of manifest.components){
      expect(component.propDetails.map(item=>item.name)).toEqual(component.props)
      expect(component.emitDetails.map(item=>item.name)).toEqual(component.emits)
      expect(component.slotDetails.map(item=>item.name)).toEqual(component.slots)
      expect(component.imports.root).toContain(component.name)
    }
    const button=manifest.components.find(component=>component.name==='UiButton')
    expect(button.propDetails.find(prop=>prop.name==='variant')).toMatchObject({type:'UiButtonVariant',default:{kind:'literal',value:'"primary"'}})
    expect(button.props).toEqual(expect.arrayContaining(['variant','size','icon','iconPosition','iconSize','loading','loadingText','disabled','type','block','shape','href','target','rel','download','autofocus','form','name','value','action','preventDefault','stopPropagation','ariaLabel','pressed']))
    expect(button.emits).toEqual(['action-error','action-start','action-success','click'])
    expect(button.slots).toEqual(['default','icon','loading','prefix','suffix'])
    const tour=manifest.components.find(component=>component.name==='UiTour')
    expect(tour.props).toContain('targetClickable')
    expect(tour.emits).toContain('target-missing')
    expect(tour.slots).toEqual(['actions','description','indicator','title'])
    const watermark=manifest.components.find(component=>component.name==='UiWatermark')
    expect(watermark.props).toEqual(expect.arrayContaining(['content','font','gap','image','observe']))
    expect(watermark.emits).toEqual(['image-error','image-load','remove','render'])
    expect(watermark.slots).toEqual(['default'])
    const affix=manifest.components.find(component=>component.name==='UiAffix')
    expect(affix.props).toEqual(['boundary','disabled','observe','offset','position','target','zIndex'])
    expect(affix.emits).toEqual(['change','error','scroll'])
    expect(affix.slots).toEqual(['default'])
    const carousel=manifest.components.find(component=>component.name==='UiCarousel')
    expect(carousel.props).toEqual(expect.arrayContaining(['items','effect','autoplay','arrows','indicators','swipe']))
    expect(carousel.emits).toEqual(expect.arrayContaining(['change','play','pause','drag-end']))
    expect(carousel.slots).toEqual(['empty','indicator','item','next-icon','previous-icon'])
    const timeRange=manifest.components.find(component=>component.name==='UiTimeRangePicker')
    expect(timeRange.props).toEqual(expect.arrayContaining(['modelValue','valueType','timeZone','step','min','max','constrain']))
    expect(timeRange.emits).toEqual(['blur','change','clear','focus','invalid','update:modelValue'])
    expect(timeRange.slots).toEqual([])
    const card=manifest.components.find(component=>component.name==='UiCard')
    expect(card.props).toEqual(expect.arrayContaining(['as','subtitle','variant','shadow','interactive','selected','disabled','loading','href','ariaLabel']))
    expect(card.emits).toEqual(['activate','click'])
    expect(card.slots).toEqual(['action','actions','cover','default','footer','header','loading','subtitle','title'])
    const tag=manifest.components.find(component=>component.name==='UiTag')
    expect(tag.props).toEqual(expect.arrayContaining(['as','color','type','variant','size','dot','round','closable','disabled','interactive','checkable','checked','href','ariaLabel']))
    expect(tag.emits).toEqual(['activate','change','click','close','update:checked'])
    expect(tag.slots).toEqual(['close-icon','default','prefix','suffix'])
    const steps=manifest.components.find(component=>component.name==='UiSteps')
    expect(steps.props).toEqual(expect.arrayContaining(['items','itemKey','modelValue','current','defaultCurrent','interactive','linear','keyboard','loop','direction','labelPlacement','type','size','status','responsive','loading','ariaLabel']))
    expect(steps.emits).toEqual(['change','item-click','item-focus','update:current','update:modelValue'])
    expect(steps.slots).toEqual(['description','empty','icon','item','loading','subtitle','title'])
    const timeline=manifest.components.find(component=>component.name==='UiTimeline')
    expect(timeline.props).toEqual(expect.arrayContaining(['items','itemKey','modelValue','defaultValue','selectable','interactive','orientation','placement','timePosition','line','pending','loading','ariaLabel']))
    expect(timeline.emits).toEqual(['activate','change','item-click','item-focus','update:modelValue'])
    expect(timeline.slots).toEqual(['description','dot','empty','item','opposite','pending','time','title'])
  })

  it('covers every component exactly once across stable documentation categories',()=>{
    expect(docs).toEqual(publicDocs)
    expect(docs.schemaVersion).toBe(1)
    expect(docs.categories).toHaveLength(6)
    expect(docs.categories.reduce((sum,category)=>sum+category.count,0)).toBe(89)
    expect(new Set(docs.components.map(component=>component.name)).size).toBe(89)
    expect(docs.components.every(component=>docs.categories.some(category=>category.id===component.category))).toBe(true)
  })

  it('generates portable Markdown with imports, props, events and slots',()=>{
    expect(markdown).toContain('Generated from `api-manifest.json` schema 3')
    expect(markdown).toContain("import { UiUpload } from 'lan-ui-design-system'")
    expect(markdown).toContain('#### Events · `UiUploadEmits`')
    expect(markdown).toContain('#### Slots · `UiUploadSlots`')
    expect(markdown).toContain("import { UiTour } from 'lan-ui-design-system'")
    expect(markdown).toContain("import { UiWatermark } from 'lan-ui-design-system'")
    expect(markdown).toContain("import { UiAffix } from 'lan-ui-design-system'")
    expect(markdown).toContain("import { UiCarousel } from 'lan-ui-design-system'")
    expect(markdown).toContain("import { UiTimeRangePicker } from 'lan-ui-design-system'")
    expect(markdown).toContain("import { UiCard } from 'lan-ui-design-system'")
    expect(markdown).toContain("import { UiTag } from 'lan-ui-design-system'")
    expect(markdown).toContain("import { UiSteps } from 'lan-ui-design-system'")
    expect(markdown).toContain("import { UiTimeline } from 'lan-ui-design-system'")
    expect(markdown).toContain("import { UiButton } from 'lan-ui-design-system'")
    expect(markdown).toContain('#### Events · `UiButtonEmits`')
    expect(markdown).toContain('#### Slots · `UiButtonSlots`')
  })

  it('filters the browser index and opens a deep-linkable API contract',async()=>{
    const wrapper=mount(ApiReferencePage,{attachTo:document.body})
    mounted.push(wrapper)
    await wrapper.get('input[aria-label="搜索组件 API"]').setValue('Upload')
    expect(wrapper.findAll('.api-reference-index nav button')).toHaveLength(1)
    await wrapper.get('.api-reference-index nav button').trigger('click')
    expect(wrapper.get('.api-reference-detail h2').text()).toBe('UiUpload')
    expect(location.hash).toBe('#/api?component=UiUpload')
    expect(wrapper.text()).toContain('autoUpload')
    expect(wrapper.text()).toContain('update:modelValue')
  })

  it('keeps generated docs behind package drift gates and app routing',()=>{
    const packageJson=JSON.parse(readFileSync(resolve(root,'package.json'),'utf8'))
    const app=readFileSync(resolve(root,'src/App.vue'),'utf8')
    expect(packageJson.scripts['api:check']).toContain('api-docs.mjs')
    expect(packageJson.scripts.prepack).toContain('api:check')
    expect(app).toContain("'/api': { title:'API 参考'")
    expect(app).toContain("split('?')[0]")
  })
})
