// @vitest-environment happy-dom
import { h, nextTick, ref } from 'vue'
import { flushPromises, mount } from '@vue/test-utils'
import { describe, expect, it, vi } from 'vitest'
import UiFloatButton from '../src/components/UiFloatButton.vue'
import UiFloatButtonGroup from '../src/components/UiFloatButtonGroup.vue'
import { lanUiTeleportScopeKey } from '../src/theme-scope.js'

describe('UiFloatButton P82 production family',()=>{
  it('preserves the native button contract and exposes typed states',async()=>{
    const wrapper=mount(UiFloatButton,{props:{icon:'plus',label:'New task',badge:120,badgeMax:99,actionKey:'new',teleportTo:false},slots:{default:()=>h('span',{class:'description'},'Create a task')}})
    const button=wrapper.get('[data-ui-float-button]')
    expect(button.element.tagName).toBe('BUTTON');expect(button.attributes('type')).toBe('button');expect(button.attributes('aria-label')).toBe('New task');expect(button.attributes('data-state')).toBe('ready');expect(wrapper.get('.ui-float-badge').text()).toBe('99+');expect(wrapper.get('.ui-sr-only').text()).toBe('120')
    await button.trigger('click',{detail:1});expect(wrapper.emitted('click')).toHaveLength(1);expect(wrapper.emitted('action')?.[0]?.[0]).toEqual(expect.objectContaining({key:'new',source:'pointer',nativeEvent:expect.any(MouseEvent)}));expect(wrapper.vm.getState()).toMatchObject({visible:true,disabled:false,active:false})
    expect(wrapper.vm.focus()).toBe(true);expect(wrapper.vm.getElement()).toBe(button.element);expect(wrapper.vm.blur()).toBe(true)
  })
  it('renders links, blocks disabled/loading activation, and supports accessible tooltip and slots',async()=>{
    const action=vi.fn();const active=mount(UiFloatButton,{props:{href:'/reports',target:'_blank',tooltip:'Open reports',ariaLabel:'Reports',actionKey:'reports',teleportTo:false},slots:{icon:()=>h('b',{class:'custom-icon'},'I'),tooltip:({open})=>h('i',{class:'custom-tip'},String(open)),badge:({value})=>h('em',{class:'custom-badge'},value)}})
    expect(active.get('[data-ui-float-button]').element.tagName).toBe('A');expect(active.get('[data-ui-float-button]').attributes('rel')).toContain('noopener');await nextTick();active.get('[data-ui-float-button]').trigger('focus');await nextTick();expect(active.get('.ui-tooltip').exists()).toBe(true)
    const blocked=mount(UiFloatButton,{props:{href:'#blocked',disabled:true,onAction:action,teleportTo:false}});expect(blocked.get('[data-ui-float-button]').attributes('href')).toBeUndefined();await blocked.get('[data-ui-float-button]').trigger('click');expect(blocked.emitted('action')).toBeUndefined();expect(action).not.toHaveBeenCalled()
    const loading=mount(UiFloatButton,{props:{loading:true,teleportTo:false}});expect(loading.get('[data-ui-float-button]').attributes('aria-busy')).toBe('true');expect(loading.get('.spinner').exists()).toBe(true)
  })
  it('supports controlled visibility and back-top target cleanup with reduced motion',async()=>{
    const scroller=document.createElement('div');Object.defineProperty(scroller,'scrollTop',{value:0,writable:true});document.body.append(scroller);const changes=vi.fn();const wrapper=mount(UiFloatButton,{props:{backTop:true,scrollTarget:scroller,visibilityHeight:40,defaultVisible:false,smooth:true,onVisibleChange:changes,teleportTo:false}});expect(wrapper.vm.getState().visible).toBe(false);scroller.scrollTop=80;scroller.dispatchEvent(new Event('scroll'));await nextTick();expect(wrapper.vm.getState().visible).toBe(true);await wrapper.vm.scrollToTop();expect(scroller.scrollTop).toBe(0);expect(wrapper.emitted('back-top')).toHaveLength(1);const visibleEvents=changes.mock.calls.length;wrapper.unmount();scroller.scrollTop=80;scroller.dispatchEvent(new Event('scroll'));expect(changes.mock.calls.length).toBe(visibleEvents)
  })
  it('provides group registration, guard serialization, selection and focus restoration',async()=>{
    let resolveGuard;const guard=vi.fn(value=>value&&guard.mock.calls.length===1?new Promise(resolve=>{resolveGuard=resolve}):true);const selected=vi.fn();const wrapper=mount(UiFloatButtonGroup,{props:{beforeOpenChange:guard,onSelect:selected,teleportTo:false},slots:{default:()=>[h(UiFloatButton,{label:'First',actionKey:'first',teleportTo:false}),h(UiFloatButton,{label:'Second',actionKey:'second',teleportTo:false}),h(UiFloatButton,{label:'Blocked',disabled:true,actionKey:'blocked',teleportTo:false})]}})
    await wrapper.get('.ui-float-button-group-trigger').trigger('click');expect(guard).toHaveBeenCalledWith(true,expect.objectContaining({source:'click'}));expect(wrapper.vm.pending).toBe(true);wrapper.vm.show('api');resolveGuard(true);await flushPromises();await nextTick();expect(wrapper.vm.getState()).toMatchObject({open:true,pending:false,actions:3});const actions=wrapper.findAll('[data-ui-float-button]');expect(actions.length).toBe(3);await actions[0].trigger('click');await nextTick();expect(selected).toHaveBeenCalledWith(expect.objectContaining({key:'first'}));expect(wrapper.vm.getState().open).toBe(false);await wrapper.vm.show('api');await nextTick();expect(wrapper.vm.focusFirst()).toBe(true);await wrapper.get('.ui-float-button-group-trigger').trigger('keydown',{key:'Escape'});await nextTick();expect(wrapper.vm.getState().open).toBe(false)
  })
  it('renders safely in SSR without browser globals',async()=>{const { renderToString }=await import('vue/server-renderer');const html=await renderToString(h(UiFloatButtonGroup,{ariaLabel:'Actions'},()=>h(UiFloatButton,{label:'New'})));expect(html).toContain('ui-float-button-group');expect(html).toContain('aria-expanded="false"')})
  it('treats false guards as ordinary denials and only reports thrown guards',async()=>{
    const denied=mount(UiFloatButtonGroup,{props:{teleportTo:false,beforeOpenChange:()=>false}})
    await denied.vm.show('api');await flushPromises();expect(denied.vm.getState()).toMatchObject({open:false,pending:false});expect(denied.emitted('guard-error')).toBeUndefined();expect(denied.emitted('open-change')).toBeUndefined()
    const error=new Error('boom');const rejected=mount(UiFloatButtonGroup,{props:{teleportTo:false,beforeOpenChange:()=>{throw error}}});await rejected.vm.show('api');await flushPromises();expect(rejected.emitted('guard-error')?.[0]).toEqual([error,expect.objectContaining({open:true,pending:false})]);expect(rejected.vm.getState().open).toBe(false)
  })
  it('serializes the latest queued transition without duplicate guard events',async()=>{
    let resolve;const guard=vi.fn(value=>guard.mock.calls.length===1?new Promise(r=>{resolve=r}):true);const wrapper=mount(UiFloatButtonGroup,{props:{teleportTo:false,beforeOpenChange:guard}})
    void wrapper.vm.show('first');await nextTick();expect(wrapper.vm.pending).toBe(true);wrapper.vm.hide('middle');wrapper.vm.show('latest');resolve(true);await flushPromises();await nextTick();expect(guard).toHaveBeenCalledTimes(1);expect(wrapper.vm.getState()).toMatchObject({open:true,pending:false});expect(wrapper.emitted('guard-error')).toBeUndefined()
    const closeGuard=vi.fn(value=>closeGuard.mock.calls.length===1?new Promise(r=>{resolve=r}):true);const close=mount(UiFloatButtonGroup,{props:{teleportTo:false,defaultOpen:false,beforeOpenChange:closeGuard}});void close.vm.show('open');await nextTick();close.vm.hide('latest-close');resolve(true);await flushPromises();await nextTick();expect(closeGuard).toHaveBeenCalledTimes(2);expect(close.vm.getState()).toMatchObject({open:false,pending:false})
  })
  it('replaces the fallback trigger with a binding-safe custom control and restores focus',async()=>{
    const wrapper=mount(UiFloatButtonGroup,{props:{teleportTo:false,ariaLabel:'Actions'},attachTo:document.body,slots:{trigger:scope=>h('button',{...scope.attrs,class:'custom-trigger'},'Custom')}})
    const trigger=wrapper.get('.custom-trigger');expect(wrapper.find('.ui-float-button-group-trigger').exists()).toBe(false);expect(wrapper.findAll('button')).toHaveLength(1);expect(trigger.attributes('aria-controls')).toBeTruthy();expect(trigger.attributes('aria-expanded')).toBe('false');trigger.element.focus();await trigger.trigger('click');await flushPromises();await nextTick();expect(wrapper.vm.getState().open).toBe(true);await trigger.trigger('keydown',{key:'Escape'});await flushPromises();await nextTick();expect(wrapper.vm.getState().open).toBe(false);expect(document.activeElement?.classList.contains('custom-trigger')).toBe(true);wrapper.unmount()
  })
  it('handles each action key once and supports real standalone/group teleport scopes',async()=>{
    const focusSpy=vi.spyOn(HTMLElement.prototype,'focus');const showSecond=ref(true);const wrapper=mount(UiFloatButtonGroup,{props:{teleportTo:false,defaultOpen:true},attachTo:document.body,slots:{default:()=>[h(UiFloatButton,{label:'One',actionKey:'one',teleportTo:false}),showSecond.value?h(UiFloatButton,{label:'Two',actionKey:'two',teleportTo:false}):null,h(UiFloatButton,{label:'Blocked',actionKey:'blocked',disabled:true,teleportTo:false}),h(UiFloatButton,{label:'Busy',actionKey:'busy',loading:true,teleportTo:false})]}});await nextTick();const actions=wrapper.findAll('[data-ui-float-button]');expect(actions).toHaveLength(4);actions[0].element.focus();focusSpy.mockClear();await actions[0].trigger('keydown',{key:'ArrowDown'});expect(focusSpy).toHaveBeenCalledTimes(1);expect(document.activeElement).toBe(actions[1].element);await actions[1].trigger('keydown',{key:'ArrowUp'});expect(focusSpy).toHaveBeenCalledTimes(2);expect(document.activeElement).toBe(actions[0].element);await actions[0].trigger('keydown',{key:'End'});expect(document.activeElement).toBe(actions[1].element);await actions[1].trigger('keydown',{key:'Home'});expect(document.activeElement).toBe(actions[0].element);showSecond.value=false;await nextTick();expect(wrapper.vm.getState().actions).toBe(3);showSecond.value=true;await nextTick();expect(wrapper.vm.getState().actions).toBe(4);const remounted=wrapper.findAll('[data-ui-float-button]');expect(remounted).toHaveLength(4);remounted[0].element.focus();await remounted[0].trigger('keydown',{key:'End'});expect(document.activeElement).toBe(remounted[1].element);wrapper.unmount()
    const scope={direction:'rtl',resolvedAppearance:'dark',appearance:'dark',themeName:'test',locale:'en-US',size:'md',density:'compact',motion:'full',resolvedMotion:'full',style:{'--portal-test':'1'}};const target=document.createElement('div');const groupTarget=document.createElement('div');document.body.append(target,groupTarget);const button=mount(UiFloatButton,{props:{teleportTo:target,ariaLabel:'Remote',fixed:true},global:{provide:{[lanUiTeleportScopeKey]:scope}}});const group=mount(UiFloatButtonGroup,{props:{teleportTo:groupTarget,ariaLabel:'Remote actions'},global:{provide:{[lanUiTeleportScopeKey]:scope}}});await nextTick();expect(target.querySelector('[data-ui-float-button]')).toBeTruthy();expect(target.querySelector('.ui-float-button-teleport-scope')?.getAttribute('dir')).toBe('rtl');expect(groupTarget.querySelector('[data-ui-float-button-group]')).toBeTruthy();expect(groupTarget.querySelector('[data-ui-float-button-group]')?.getAttribute('dir')).toBe('rtl');button.unmount();group.unmount();expect(target.querySelector('[data-ui-float-button]')).toBeNull();expect(groupTarget.querySelector('[data-ui-float-button-group]')).toBeNull()
  })
  it('keeps legacy standalone buttons inline and lets the group own child placement',async()=>{
    const host=document.createElement('div');const explicitTarget=document.createElement('div');document.body.append(host,explicitTarget)
    const legacy=mount(UiFloatButton,{props:{label:'Inline legacy'},attachTo:host});await nextTick();expect(host.querySelector('[data-ui-float-button]')).toBe(legacy.get('[data-ui-float-button]').element);expect(explicitTarget.querySelector('[data-ui-float-button]')).toBeNull()
    const explicit=mount(UiFloatButton,{props:{label:'Explicit portal',teleportTo:explicitTarget}});await nextTick();expect(explicitTarget.querySelector('[data-ui-float-button]')?.getAttribute('aria-label')).toBe('Explicit portal')
    const group=mount(UiFloatButtonGroup,{props:{defaultOpen:true,ariaLabel:'Owned actions'},attachTo:document.body,slots:{default:()=>[h(UiFloatButton,{label:'Owned one'}),h(UiFloatButton,{label:'Owned two'})]}});await nextTick();const groupRoot=document.body.querySelector('[data-ui-float-button-group]');const owned=[...groupRoot.querySelectorAll('.ui-float-button-group-actions [data-ui-float-button]')];expect(owned).toHaveLength(2);expect(owned.every(button=>groupRoot.contains(button))).toBe(true);expect(owned.some(button=>button.closest('.ui-float-button-group-actions')===null)).toBe(false)
    const inlineHost=document.createElement('div');document.body.append(inlineHost);const inlineGroup=mount(UiFloatButtonGroup,{props:{teleportTo:false},attachTo:inlineHost,slots:{default:()=>h(UiFloatButton,{label:'Inline child'})}});await nextTick();expect(inlineHost.querySelector('[data-ui-float-button-group]')).toBe(inlineGroup.find('[data-ui-float-button-group]').element);expect(inlineHost.querySelector('.ui-float-button-group-actions [data-ui-float-button]')).toBeTruthy();legacy.unmount();explicit.unmount();group.unmount();inlineGroup.unmount()
  })
  it('does not warn while rendering the portal family through SSR',async()=>{
    const { renderToString }=await import('vue/server-renderer');const warn=vi.spyOn(console,'warn').mockImplementation(()=>{});try{const html=await renderToString(h(UiFloatButtonGroup,{teleportTo:false,ariaLabel:'SSR actions'},()=>h(UiFloatButton,{label:'SSR action'})));expect(html).toContain('ui-float-button-group');expect(html).toContain('ui-float-button')}finally{warn.mockRestore()};expect(warn).not.toHaveBeenCalled()
  })
})
