<script setup>
import { computed, inject, nextTick, onBeforeUnmount, onMounted, ref, toRef, useAttrs, useId, useSlots, watch } from 'vue'
import AppIcon from './AppIcon.vue'
import { useFloatingPosition } from './floatingPosition.js'
import { focusWithRetry } from './focusUtils.js'
import { scrollElementWithin } from './scrollUtils.js'
import { useComponentSize, useDirection, useLanUiConfig, useLocale } from '../config-runtime.js'
import { useTeleportThemeScope } from '../theme-scope.js'

defineOptions({ inheritAttrs:false })
const props=defineProps({
  modelValue:{type:[String,Number,Array],default:undefined},defaultValue:{type:[String,Number,Array],default:undefined},open:{type:Boolean,default:undefined},defaultOpen:Boolean,
  options:{type:Array,default:()=>[]},fieldNames:{type:Object,default:()=>({})},placeholder:{type:String,default:''},size:{type:String,default:''},disabled:Boolean,readonly:Boolean,invalid:Boolean,loading:Boolean,clearable:Boolean,clearValue:{type:[String,Number],default:''},
  multiple:Boolean,checkStrictly:Boolean,changeOnSelect:Boolean,emitPath:{type:Boolean,default:true},showAllLevels:{type:Boolean,default:true},separator:{type:String,default:' / '},activePath:{type:Array,default:undefined},defaultActivePath:{type:Array,default:()=>[]},
  expandTrigger:{type:String,default:'click',validator:value=>['click','hover'].includes(value)},searchable:Boolean,filterOption:{type:[Boolean,Function],default:true},loadData:Function,closeOnSelect:{type:Boolean,default:undefined},
  maxCount:{type:Number,default:Infinity},minCount:{type:Number,default:0},maxTagCount:{type:Number,default:3},emptyText:{type:String,default:''},loadingText:{type:String,default:''},errorText:{type:String,default:''},searchPlaceholder:{type:String,default:''},
  placement:{type:String,default:'bottom-start',validator:value=>['top-start','top-end','bottom-start','bottom-end'].includes(value)},appendToBody:{type:Boolean,default:true},name:String,form:String,required:Boolean,autofocus:Boolean,ariaLabel:String,
})
const emit=defineEmits(['update:modelValue','update:open','update:activePath','input','change','select','deselect','clear','search','open-change','active-path-change','load','load-error','invalid','focus','blur'])
const attrs=useAttrs(),slots=useSlots(),formItem=inject('uiFormItemContext',null),uid=useId()
const rootRef=ref(null),triggerRef=ref(null),panelRef=ref(null),searchInputRef=ref(null),nativeRef=ref(null)
const internalValue=ref(props.modelValue===undefined?(props.defaultValue===undefined?emptyValue():props.defaultValue):props.modelValue)
const internalOpen=ref(props.defaultOpen),internalActivePath=ref([...props.defaultActivePath]),activeColumn=ref(0),activeIndex=ref(0),query=ref(''),focused=ref(false),composing=ref(false),dropUp=ref(false)
const loadedChildren=ref(new Map()),loadingKeys=ref([]),loadErrors=ref(new Map()),selectedMemory=ref(new Map()),loadControllers=new Map(),loadSequences=new Map()
let resetForm=null,typeahead='',typeaheadTimer=null
const {portalThemeAttrs,portalThemeStyle}=useTeleportThemeScope(),config=useLanUiConfig(),direction=useDirection(),{t}=useLocale(),resolvedSize=useComponentSize(toRef(props,'size'))
const fieldMap=computed(()=>Object.freeze({label:props.fieldNames.label||'label',value:props.fieldNames.value||'value',children:props.fieldNames.children||'children',disabled:props.fieldNames.disabled||'disabled',isLeaf:props.fieldNames.isLeaf||'isLeaf',icon:props.fieldNames.icon||'icon',description:props.fieldNames.description||'description',keywords:props.fieldNames.keywords||'keywords'}))

function emptyValue(){return props?.multiple?[]:(props?.emitPath===false?props?.clearValue??'':[])}
function valuesEqual(a,b){return Object.is(a,b)}
function pathsEqual(a,b){return Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.every((value,index)=>valuesEqual(value,b[index]))}
function pathKey(path){return JSON.stringify((Array.isArray(path)?path:[]).map(value=>[typeof value,String(value)]))}
function uniquePaths(paths){const seen=new Set();return paths.filter(path=>{const key=pathKey(path);if(!path.length||seen.has(key))return false;seen.add(key);return true})}
function sourceChildren(raw,key){if(loadedChildren.value.has(key))return loadedChildren.value.get(key);const children=raw&&typeof raw==='object'?raw[fieldMap.value.children]:[];return Array.isArray(children)?children:[]}
const treeModel=computed(()=>{
  const records=[]
  function walk(nodes,parent=null,pathValues=[],pathLabels=[]){return (Array.isArray(nodes)?nodes:[]).map(raw=>{
    const value=raw&&typeof raw==='object'?(raw[fieldMap.value.value]??raw[fieldMap.value.label]):raw,label=String(raw&&typeof raw==='object'?(raw[fieldMap.value.label]??value??''):(raw??'')),values=[...pathValues,value],labels=[...pathLabels,label],key=pathKey(values),children=sourceChildren(raw,key),explicitLeaf=Boolean(raw&&typeof raw==='object'&&raw[fieldMap.value.isLeaf]===true),keywords=raw&&typeof raw==='object'?raw[fieldMap.value.keywords]:[]
    const record={raw,value,label,key,parent,pathValues:values,pathLabels:labels,children:[],level:values.length,disabled:Boolean(raw&&typeof raw==='object'&&raw[fieldMap.value.disabled]),isLeaf:explicitLeaf,branch:!explicitLeaf&&(children.length>0||Boolean(props.loadData)),icon:raw&&typeof raw==='object'?raw[fieldMap.value.icon]:undefined,description:String(raw&&typeof raw==='object'?(raw[fieldMap.value.description]??''):''),keywords:Array.isArray(keywords)?keywords:keywords==null?[]:[keywords]}
    records.push(record);record.children=walk(children,record,values,labels);return record
  })}
  return {roots:walk(props.options),records}
})
function findPath(path){if(!Array.isArray(path)||!path.length)return null;let nodes=treeModel.value.roots,record=null;for(const value of path){record=nodes.find(item=>valuesEqual(item.value,value))||null;if(!record)return null;nodes=record.children}return record}
function findValue(value){return treeModel.value.records.find(record=>valuesEqual(record.value,value)&&(!record.branch||props.changeOnSelect||props.checkStrictly))||treeModel.value.records.find(record=>valuesEqual(record.value,value))||null}
function publicNode(record){return record?{label:record.label,value:record.value,disabled:record.disabled,isLeaf:!record.branch,icon:record.icon,description:record.description,pathValues:[...record.pathValues],pathLabels:[...record.pathLabels],level:record.level,raw:record.raw}:undefined}
function normalizeToPaths(value){if(props.multiple){if(!Array.isArray(value))return [];return props.emitPath?uniquePaths(value.filter(Array.isArray).map(path=>[...path])):uniquePaths(value.map(item=>findValue(item)?.pathValues).filter(Boolean))}if(props.emitPath)return Array.isArray(value)&&value.length?[[...value]]:[];const record=findValue(value);return record?[[...record.pathValues]]:[]}
function toExternal(paths){const next=uniquePaths(paths.map(path=>[...path]));if(props.multiple)return props.emitPath?next:next.map(path=>path.at(-1));const path=next[0];if(!path)return props.emitPath?[]:props.clearValue;return props.emitPath?path:path.at(-1)}
const resolvedRawValue=computed(()=>props.modelValue===undefined?internalValue.value:props.modelValue),selectedPaths=computed(()=>normalizeToPaths(resolvedRawValue.value)),resolvedValue=computed(()=>toExternal(selectedPaths.value))
const selectedRecords=computed(()=>selectedPaths.value.map(path=>findPath(path)||selectedMemory.value.get(pathKey(path))||{label:String(path.at(-1)??''),value:path.at(-1),disabled:false,branch:false,icon:undefined,description:'',pathValues:path,pathLabels:path.map(String),level:path.length,raw:null}))
const resolvedOpen=computed(()=>props.open===undefined?internalOpen.value:props.open),resolvedActivePath=computed(()=>props.activePath===undefined?internalActivePath.value:props.activePath)
const resolvedInvalid=computed(()=>props.invalid||formItem?.invalid?.value||false),resolvedRequired=computed(()=>props.required||formItem?.required?.value||false)
const resolvedPlaceholder=computed(()=>props.placeholder||t('cascader.placeholder')),resolvedEmptyText=computed(()=>props.emptyText||t('cascader.empty')),resolvedLoadingText=computed(()=>props.loadingText||t('cascader.loading')),resolvedErrorText=computed(()=>props.errorText||t('cascader.loadError')),resolvedSearchPlaceholder=computed(()=>props.searchPlaceholder||t('cascader.search'))
const controlId=computed(()=>attrs.id||formItem?.controlId?.value||`ui-cascader-${uid}`),menuId=`ui-cascader-menu-${uid}`
const labelledby=computed(()=>attrs['aria-labelledby']||(attrs['aria-label']||props.ariaLabel?undefined:formItem?.labelId?.value)),describedby=computed(()=>attrs['aria-describedby']||formItem?.describedby?.value||undefined),resolvedAriaLabel=computed(()=>props.ariaLabel||attrs['aria-label']||undefined)
const passthroughAttrs=computed(()=>Object.fromEntries(Object.entries(attrs).filter(([key])=>!['id','class','style','name','form','required','autofocus','disabled','readonly','aria-label','aria-labelledby','aria-describedby','aria-invalid','aria-required','aria-busy','role','tabindex'].includes(key))))
const maxSelectionCount=computed(()=>Number.isFinite(props.maxCount)?Math.max(0,Math.floor(props.maxCount)):Infinity),minSelectionCount=computed(()=>Number.isFinite(props.minCount)?Math.max(0,Math.floor(props.minCount)):0),visibleTagCount=computed(()=>Math.max(0,Math.floor(Number.isFinite(props.maxTagCount)?props.maxTagCount:3)))
const visibleSelectedRecords=computed(()=>selectedRecords.value.slice(0,visibleTagCount.value)),hiddenTagCount=computed(()=>Math.max(0,selectedRecords.value.length-visibleSelectedRecords.value.length)),hasValue=computed(()=>selectedPaths.value.length>0),displayLabel=computed(()=>selectedRecords.value[0]?formatLabel(selectedRecords.value[0]):''),hasPrefix=computed(()=>Boolean(slots.prefix)),hasSuffix=computed(()=>Boolean(slots.suffix)),hasActions=computed(()=>Boolean(props.loading||(props.clearable&&hasValue.value&&!props.disabled&&!props.readonly))),resolvedCloseOnSelect=computed(()=>props.closeOnSelect===undefined?!props.multiple:props.closeOnSelect)
const state=computed(()=>props.disabled?'disabled':props.readonly?'readonly':props.loading?'loading':resolvedInvalid.value?'invalid':resolvedOpen.value?'open':focused.value?'focused':'ready')
function formatLabel(record){return props.showAllLevels?record.pathLabels.join(props.separator):record.label}
const columns=computed(()=>{const result=[treeModel.value.roots];let nodes=treeModel.value.roots;for(const value of resolvedActivePath.value){const record=nodes.find(item=>valuesEqual(item.value,value));if(!record)break;nodes=record.children;if(nodes.length)result.push(nodes);else break}return result})
function matchesRecord(record,text){if(props.filterOption===false)return true;if(typeof props.filterOption==='function'){try{return props.filterOption(String(text),publicNode(record))!==false}catch{return false}}const needle=String(text??'').trim().toLocaleLowerCase();if(!needle)return true;return [record.label,record.value,record.description,...record.keywords,...record.pathLabels].map(value=>String(value??'').toLocaleLowerCase()).some(value=>value.includes(needle))}
const searchResults=computed(()=>!props.searchable||!query.value.trim()?[]:treeModel.value.records.filter(record=>(!record.branch||props.changeOnSelect||props.checkStrictly)&&matchesRecord(record,query.value))),searchMode=computed(()=>props.searchable&&Boolean(query.value.trim())),activeOptions=computed(()=>searchMode.value?searchResults.value:(columns.value[activeColumn.value]||[]))
const optionId=(column,index)=>`ui-cascader-option-${uid}-${column}-${index}`,activeDescendant=computed(()=>!resolvedOpen.value||activeIndex.value<0?undefined:searchMode.value?optionId('search',activeIndex.value):optionId(activeColumn.value,activeIndex.value))
const menuWidth=computed(()=>`${Math.max(220,rootRef.value?.getBoundingClientRect().width||0)}px`),resolvedPlacement=computed(()=>direction.value!=='rtl'?props.placement:props.placement.endsWith('-start')?props.placement.replace(/-start$/,'-end'):props.placement.endsWith('-end')?props.placement.replace(/-end$/,'-start'):props.placement)
const {floatingStyle,resolvedPlacement:actualPlacement,update:updatePosition}=useFloatingPosition({triggerRef:rootRef,panelRef,open:computed(()=>resolvedOpen.value&&props.appendToBody),placement:resolvedPlacement,offset:6,zIndex:computed(()=>config.value.zIndex+55)})
const panelStyle=computed(()=>props.appendToBody?{...floatingStyle.value,minWidth:menuWidth.value}:undefined),opensUp=computed(()=>props.appendToBody?actualPlacement.value.startsWith('top'):dropUp.value)

function emitInvalid(reason,source,extra={}){const payload={reason,source,value:resolvedValue.value,path:[...resolvedActivePath.value],query:query.value,...extra};emit('invalid',payload);return false}
function setActivePath(path,source='api',nativeEvent){const next=Array.isArray(path)?[...path]:[],previous=[...resolvedActivePath.value];if(pathsEqual(next,previous))return false;if(props.activePath===undefined)internalActivePath.value=next;const meta={source,previous,next,nativeEvent};emit('update:activePath',next);emit('active-path-change',next,meta);nextTick(updatePosition);return meta}
function enabledIndex(options,start,delta){if(!options.length)return -1;let index=start;for(let count=0;count<options.length;count+=1){index=(index+delta+options.length)%options.length;if(!options[index]?.disabled)return index}return -1}
function resetActive(){if(searchMode.value){activeColumn.value=0;activeIndex.value=enabledIndex(searchResults.value,-1,1);return}const preferred=selectedPaths.value[0]||resolvedActivePath.value;if(preferred.length&&props.activePath===undefined&&!pathsEqual(preferred,internalActivePath.value))internalActivePath.value=[...preferred];const preferredRecord=findPath(preferred),preferredColumn=preferredRecord?.branch?preferred.length:preferred.length-1;activeColumn.value=Math.max(0,Math.min(columns.value.length-1,preferredColumn));const options=columns.value[activeColumn.value]||[],selectedIndex=options.findIndex(item=>valuesEqual(item.value,preferred[activeColumn.value])&&!item.disabled);activeIndex.value=selectedIndex>=0?selectedIndex:enabledIndex(options,-1,1);nextTick(scrollToActive)}
function prepareOpen(){const rect=rootRef.value?.getBoundingClientRect(),viewport=typeof innerHeight==='number'?innerHeight:0;dropUp.value=props.placement.startsWith('top')||Boolean(rect&&viewport-rect.bottom<280&&rect.top>280);resetActive();nextTick(()=>{updatePosition();focusWithRetry(()=>props.searchable?searchInputRef.value:triggerRef.value)})}
function cleanupClose({focusTrigger=false}={}){activeIndex.value=-1;if(query.value){query.value='';emit('search','',{source:'close'})}if(focusTrigger)nextTick(()=>focusWithRetry(()=>triggerRef.value))}
function setOpen(value,source='api',nativeEvent){const next=Boolean(value),previous=resolvedOpen.value;if(props.disabled)return emitInvalid('disabled',source,{nativeEvent});if(props.readonly&&next)return emitInvalid('readonly',source,{nativeEvent});if(next===previous){if(next)resetActive();return false}if(props.open===undefined)internalOpen.value=next;const meta={source,previous,query:query.value,nativeEvent};emit('update:open',next);emit('open-change',next,meta);if(next)prepareOpen();else cleanupClose({focusTrigger:source==='escape'});return meta}
function toggleOpen(source='api',nativeEvent){return setOpen(!resolvedOpen.value,source,nativeEvent)}
function setLoading(key,loading){const next=loadingKeys.value.filter(item=>item!==key);if(loading)next.push(key);loadingKeys.value=next}
function isLoading(record){return loadingKeys.value.includes(record.key)}
async function loadNode(record,{source='api',force=false,nativeEvent}={}){if(!record||!props.loadData||record.isLeaf)return [];if(!force&&loadedChildren.value.has(record.key))return loadedChildren.value.get(record.key);loadControllers.get(record.key)?.abort();const sequence=(loadSequences.get(record.key)||0)+1;loadSequences.set(record.key,sequence);const controller=typeof AbortController==='undefined'?null:new AbortController();loadControllers.set(record.key,controller);setLoading(record.key,true);const errors=new Map(loadErrors.value);errors.delete(record.key);loadErrors.value=errors;try{const result=await props.loadData(publicNode(record),{signal:controller?.signal,source});if(loadSequences.get(record.key)!==sequence||controller?.signal.aborted)return [];const children=Array.isArray(result)?result:[],loaded=new Map(loadedChildren.value);loaded.set(record.key,children);loadedChildren.value=loaded;emit('load',{node:publicNode(record),children,source});nextTick(()=>{resetActive();updatePosition()});return children}catch(error){if(loadSequences.get(record.key)!==sequence||error?.name==='AbortError'||controller?.signal.aborted)return [];const nextErrors=new Map(loadErrors.value);nextErrors.set(record.key,error);loadErrors.value=nextErrors;const payload={node:publicNode(record),error,source};emit('load-error',payload);emitInvalid('load-error',source,{error,node:publicNode(record),nativeEvent});return []}finally{if(loadSequences.get(record.key)===sequence){setLoading(record.key,false);loadControllers.delete(record.key)}}}
function reloadNode(path,source='api'){return loadNode(Array.isArray(path)?findPath(path):findValue(path),{source,force:true})}
function remember(record){if(!record?.pathValues)return;const next=new Map(selectedMemory.value);next.set(pathKey(record.pathValues),record);selectedMemory.value=next}
function isSelected(record){return selectedPaths.value.some(path=>pathsEqual(path,record.pathValues))}
function terminalRecords(record){if(props.checkStrictly||!record.branch)return [record];const descendants=[];const walk=node=>{if(!node.branch){if(!node.disabled)descendants.push(node);return}for(const child of node.children)walk(child)};walk(record);return descendants}
function checkState(record){const targets=terminalRecords(record);if(!targets.length)return {checked:isSelected(record),indeterminate:false};const count=targets.filter(isSelected).length;return {checked:count===targets.length,indeterminate:count>0&&count<targets.length}}
function pathNodes(path){return path.map((_,index)=>publicNode(findPath(path.slice(0,index+1)))).filter(Boolean)}
function commitPaths(paths,record,action,source='api',nativeEvent){const nextPaths=uniquePaths(paths),previous=resolvedValue.value,next=toExternal(nextPaths);if(props.multiple&&nextPaths.length>maxSelectionCount.value)return emitInvalid('max-count',source,{maxCount:maxSelectionCount.value,requested:next,node:publicNode(record),nativeEvent});if(props.multiple&&nextPaths.length<minSelectionCount.value)return emitInvalid('min-count',source,{minCount:minSelectionCount.value,requested:next,node:publicNode(record),nativeEvent});for(const path of nextPaths){const known=findPath(path);if(known)remember(known)}if(props.modelValue===undefined)internalValue.value=next;const pathsPayload=props.multiple?nextPaths.map(pathNodes):pathNodes(nextPaths[0]||[]),meta={action,source,node:publicNode(record),previous,next,paths:nextPaths.map(path=>[...path]),query:query.value,nativeEvent};emit('update:modelValue',next);emit('input',next,meta);emit('change',next,pathsPayload,meta);if(action==='select')emit('select',next,publicNode(record),meta);if(action==='deselect')emit('deselect',next,publicNode(record),meta);return meta}
function toggleRecord(record,source='api',nativeEvent){if(!record)return emitInvalid('unknown-node',source,{nativeEvent});if(props.loading)return emitInvalid('loading',source,{node:publicNode(record),nativeEvent});if(props.readonly)return emitInvalid('readonly',source,{node:publicNode(record),nativeEvent});if(props.disabled||record.disabled)return emitInvalid('node-disabled',source,{node:publicNode(record),nativeEvent});const targets=props.multiple?terminalRecords(record):[record];if(!targets.length)return false;if(!props.multiple){const meta=commitPaths([record.pathValues],record,'select',source,nativeEvent);if(meta!==false&&resolvedCloseOnSelect.value&&(!record.branch||props.closeOnSelect===true))setOpen(false,'select',nativeEvent);return meta}let next=selectedPaths.value.map(path=>[...path]);const removing=targets.every(item=>next.some(path=>pathsEqual(path,item.pathValues)));for(const target of targets){const index=next.findIndex(path=>pathsEqual(path,target.pathValues));if(removing&&index>=0)next.splice(index,1);else if(!removing&&index<0)next.push([...target.pathValues])}const meta=commitPaths(next,record,removing?'deselect':'select',source,nativeEvent);if(meta!==false&&resolvedCloseOnSelect.value)setOpen(false,'select',nativeEvent);return meta}
async function activateRecord(record,column,source='pointer',nativeEvent,{selectBranch=false}={}){if(!record||record.disabled)return emitInvalid('node-disabled',source,{node:publicNode(record),nativeEvent});activeColumn.value=column;activeIndex.value=(columns.value[column]||[]).findIndex(item=>item.key===record.key);if(record.branch){setActivePath(record.pathValues,source,nativeEvent);if(props.loadData&&!record.children.length)await loadNode(record,{source,nativeEvent});activeColumn.value=column+1;activeIndex.value=enabledIndex(columns.value[column+1]||[],-1,1);if(selectBranch&&(props.changeOnSelect||props.checkStrictly))toggleRecord(record,source,nativeEvent);nextTick(scrollToActive);return true}setActivePath(record.pathValues,source,nativeEvent);return toggleRecord(record,source,nativeEvent)}
function selectPath(path,source='api'){return toggleRecord(Array.isArray(path)?findPath(path):findValue(path),source)}
function remove(path,source='api'){const target=Array.isArray(path)?path:findValue(path)?.pathValues;if(!target||!selectedPaths.value.some(item=>pathsEqual(item,target)))return false;return commitPaths(selectedPaths.value.filter(item=>!pathsEqual(item,target)),findPath(target)||selectedMemory.value.get(pathKey(target)),'deselect',source)}
function clear(source='api',nativeEvent){if(props.disabled)return emitInvalid('disabled',source,{nativeEvent});if(props.readonly)return emitInvalid('readonly',source,{nativeEvent});if(props.multiple&&minSelectionCount.value>0)return emitInvalid('min-count',source,{minCount:minSelectionCount.value,nativeEvent});const previous=resolvedValue.value,next=emptyValue();if(props.modelValue===undefined)internalValue.value=next;const meta={action:'clear',source,previous,next,paths:[],query:query.value,nativeEvent};emit('update:modelValue',next);emit('input',next,meta);emit('change',next,[],meta);emit('clear',meta);selectedMemory.value=new Map();return meta}
function setValue(value,source='api'){return commitPaths(normalizeToPaths(value),null,'set',source)}
function clearFromControl(event){event.preventDefault();event.stopPropagation();clear('clear',event)}
function removeTag(record,event){event.preventDefault();event.stopPropagation();remove(record.pathValues,'tag')}
function onSearchInput(event){query.value=event.target.value;if(composing.value||event.isComposing)return;emit('search',query.value,{source:'input'});resetActive();nextTick(updatePosition)}
function onCompositionEnd(event){composing.value=false;query.value=event.target.value;emit('search',query.value,{source:'composition'});resetActive();nextTick(updatePosition)}
function closeOutside(event){if(rootRef.value?.contains(event.target)||panelRef.value?.contains(event.target))return;setOpen(false,'outside',event)}
function scrollToActive(){if(activeIndex.value<0)return false;nextTick(()=>{if(typeof document==='undefined')return;const element=document.getElementById(searchMode.value?optionId('search',activeIndex.value):optionId(activeColumn.value,activeIndex.value));scrollElementWithin(element,element?.closest('.ui-cascader-results,.ui-cascader-column'))});return true}
function moveActive(delta){activeIndex.value=enabledIndex(activeOptions.value,activeIndex.value,delta);scrollToActive()}
function moveBoundary(end=false){activeIndex.value=enabledIndex(activeOptions.value,end?0:-1,end?-1:1);scrollToActive()}
function handleTypeahead(event){if(props.searchable||event.ctrlKey||event.metaKey||event.altKey||event.key.length!==1)return false;typeahead+=event.key.toLocaleLowerCase();if(typeaheadTimer)clearTimeout(typeaheadTimer);typeaheadTimer=setTimeout(()=>{typeahead='';typeaheadTimer=null},500);if(!resolvedOpen.value)setOpen(true,'typeahead',event);const options=activeOptions.value,start=Math.max(activeIndex.value,0);for(let offset=1;offset<=options.length;offset+=1){const index=(start+offset)%options.length;if(!options[index].disabled&&options[index].label.toLocaleLowerCase().startsWith(typeahead)){activeIndex.value=index;scrollToActive();break}}return true}
async function onKeydown(event){if(props.disabled)return;if(props.readonly){if(['ArrowDown','ArrowUp','Enter',' '].includes(event.key)){event.preventDefault();emitInvalid('readonly','keyboard',{nativeEvent:event})}return}if(event.isComposing||event.keyCode===229)return;if(!resolvedOpen.value&&['ArrowDown','ArrowUp','Enter',' '].includes(event.key)){event.preventDefault();setOpen(true,'keyboard',event);return}if(!resolvedOpen.value){handleTypeahead(event);return}if(event.key==='ArrowDown'){event.preventDefault();moveActive(1);return}if(event.key==='ArrowUp'){event.preventDefault();moveActive(-1);return}if(event.key==='Home'){event.preventDefault();moveBoundary(false);return}if(event.key==='End'){event.preventDefault();moveBoundary(true);return}if(event.key==='Escape'){event.preventDefault();setOpen(false,'escape',event);return}if(event.key==='Tab'){setOpen(false,'tab',event);return}const record=activeOptions.value[activeIndex.value];if(searchMode.value){if((event.key==='Enter'||event.key===' ')&&record){event.preventDefault();toggleRecord(record,'keyboard',event)}return}const forwardKey=direction.value==='rtl'?'ArrowLeft':'ArrowRight',backKey=direction.value==='rtl'?'ArrowRight':'ArrowLeft';if(event.key===forwardKey&&record?.branch){event.preventDefault();await activateRecord(record,activeColumn.value,'keyboard',event);return}if(event.key===backKey&&activeColumn.value>0){event.preventDefault();activeColumn.value-=1;const options=columns.value[activeColumn.value]||[];activeIndex.value=Math.max(0,options.findIndex(item=>valuesEqual(item.value,resolvedActivePath.value[activeColumn.value])));scrollToActive();return}if(event.key===' '&&props.multiple&&record){event.preventDefault();toggleRecord(record,'keyboard',event);return}if((event.key==='Enter'||(event.key===' '&&event.target!==searchInputRef.value))&&record){event.preventDefault();await activateRecord(record,activeColumn.value,'keyboard',event,{selectBranch:true});return}handleTypeahead(event)}
function onOptionEnter(record,column){if(record.disabled)return;activeColumn.value=column;activeIndex.value=(columns.value[column]||[]).findIndex(item=>item.key===record.key);if(props.expandTrigger==='hover'&&record.branch)activateRecord(record,column,'hover')}
function handleFocusIn(event){if(focused.value)return;focused.value=true;emit('focus',event,{value:resolvedValue.value,path:[...resolvedActivePath.value]})}
function handleFocusOut(event){setTimeout(()=>{const active=typeof document==='undefined'?null:document.activeElement;if(rootRef.value?.contains(active)||panelRef.value?.contains(active)||!focused.value)return;focused.value=false;emit('blur',event,{value:resolvedValue.value,path:[...resolvedActivePath.value]})},0)}
function focus(options){if(props.disabled)return false;triggerRef.value?.focus(options);return Boolean(triggerRef.value)}function blur(){searchInputRef.value?.blur();triggerRef.value?.blur();return Boolean(triggerRef.value)}function show(source='api'){return setOpen(true,source)}function hide(source='api'){return setOpen(false,source)}
function onNativeInvalid(event){emitInvalid('required','native',{nativeEvent:event});nextTick(focus)}
function onFormReset(){const next=props.defaultValue===undefined?emptyValue():props.defaultValue,previous=resolvedValue.value;if(props.modelValue===undefined)internalValue.value=next;const paths=normalizeToPaths(next),meta={action:'reset',source:'reset',previous,next:toExternal(paths),paths};emit('update:modelValue',meta.next);emit('input',meta.next,meta);emit('change',meta.next,props.multiple?paths.map(pathNodes):pathNodes(paths[0]||[]),meta);if(props.activePath===undefined)internalActivePath.value=[...props.defaultActivePath];selectedMemory.value=new Map();setOpen(false,'reset')}
watch(()=>props.modelValue,value=>{if(value!==undefined)internalValue.value=value},{deep:true});watch([()=>props.multiple,()=>props.emitPath],()=>{if(props.modelValue===undefined)internalValue.value=toExternal(selectedPaths.value)});watch(()=>props.options,()=>{loadedChildren.value=new Map();loadErrors.value=new Map();nextTick(resetActive)});watch(()=>props.open,(value,previous)=>{if(value===undefined||value===previous)return;if(value)prepareOpen();else cleanupClose()});watch([columns,searchResults],()=>{if(resolvedOpen.value)resetActive()})
onMounted(()=>{document.addEventListener('pointerdown',closeOutside);resetForm=nativeRef.value?.form||null;resetForm?.addEventListener('reset',onFormReset);for(const record of selectedRecords.value)remember(record);if(props.autofocus)nextTick(focus);if(resolvedOpen.value)prepareOpen()})
onBeforeUnmount(()=>{document.removeEventListener('pointerdown',closeOutside);resetForm?.removeEventListener('reset',onFormReset);for(const controller of loadControllers.values())controller?.abort();loadControllers.clear();if(typeaheadTimer)clearTimeout(typeaheadTimer)})
defineExpose({root:rootRef,trigger:triggerRef,panel:panelRef,native:nativeRef,value:resolvedValue,open:resolvedOpen,activePath:resolvedActivePath,query,loadingKeys,loadErrors,focus,blur,show,hide,toggle:toggleOpen,clear,select:selectPath,remove,setValue,setActivePath,loadNode:reloadNode,scrollToActive})
</script>

<template>
  <div ref="rootRef" class="ui-cascader" :class="[`size-${resolvedSize}`,attrs.class,{open:resolvedOpen,'drop-up':opensUp,disabled,readonly,loading,invalid:resolvedInvalid,multiple,searchable,clearable,'has-prefix':hasPrefix,'has-suffix':hasSuffix,'has-actions':hasActions}]" :style="attrs.style" data-ui-cascader :data-state="state" @focusin="handleFocusIn" @focusout="handleFocusOut" @keydown="onKeydown">
    <select v-if="name||resolvedRequired" ref="nativeRef" class="ui-cascader-native" :name="name" :form="form" :required="resolvedRequired" :disabled="disabled" :multiple="multiple" tabindex="-1" aria-hidden="true" @invalid="onNativeInvalid"><option v-if="!multiple" value="" :selected="!hasValue">{{ resolvedPlaceholder }}</option><option v-for="record in selectedRecords" :key="`native-${pathKey(record.pathValues)}`" :value="record.pathValues.join(separator)" selected>{{ formatLabel(record) }}</option></select>
    <div v-bind="passthroughAttrs" :id="controlId" ref="triggerRef" class="control ui-cascader-trigger" :tabindex="disabled?-1:0" role="combobox" aria-haspopup="listbox" :aria-expanded="resolvedOpen" :aria-controls="resolvedOpen&&!loading?menuId:undefined" :aria-activedescendant="!searchable?activeDescendant:undefined" :aria-autocomplete="searchable?'list':undefined" :aria-label="resolvedAriaLabel" :aria-labelledby="labelledby" :aria-describedby="describedby" :aria-disabled="disabled||undefined" :aria-readonly="readonly||undefined" :aria-invalid="resolvedInvalid||undefined" :aria-required="resolvedRequired||undefined" :aria-busy="loading||undefined" @click="toggleOpen('pointer',$event)">
      <span v-if="hasPrefix" class="ui-cascader-affix ui-cascader-prefix"><slot name="prefix" :value="resolvedValue" :paths="selectedRecords.map(publicNode)"/></span>
      <span v-if="multiple&&hasValue" class="ui-cascader-tags"><span v-for="record in visibleSelectedRecords" :key="pathKey(record.pathValues)" class="ui-cascader-tag" :class="{disabled:record.disabled}"><slot name="tag" :node="publicNode(record)" :remove="event=>removeTag(record,event)"><span class="ui-cascader-tag-label">{{ formatLabel(record) }}</span><button v-if="!disabled&&!readonly&&!record.disabled" type="button" :aria-label="t('cascader.remove',{label:record.label})" @mousedown.prevent @click="removeTag(record,$event)"><AppIcon name="close" :size="10"/></button></slot></span><span v-if="hiddenTagCount" class="ui-cascader-tag ui-cascader-overflow-tag">+{{ hiddenTagCount }}</span></span>
      <span v-else-if="hasValue" class="ui-cascader-value"><slot name="value" :node="publicNode(selectedRecords[0])" :value="resolvedValue">{{ displayLabel }}</slot></span><span v-else class="placeholder ui-cascader-placeholder"><slot name="placeholder">{{ resolvedPlaceholder }}</slot></span>
      <span v-if="hasSuffix" class="ui-cascader-affix ui-cascader-suffix"><slot name="suffix" :value="resolvedValue" :paths="selectedRecords.map(publicNode)"/></span><span class="ui-cascader-arrow" aria-hidden="true"><slot name="arrow" :open="resolvedOpen"><AppIcon name="chevronDown" :size="15"/></slot></span>
    </div>
    <span v-if="loading" class="ui-cascader-loading" role="status" :aria-label="resolvedLoadingText"><slot name="loading"><span class="spinner ui-cascader-spinner"/></slot></span><button v-else-if="clearable&&hasValue&&!disabled&&!readonly" type="button" class="ui-cascader-clear" :aria-label="t('cascader.clear')" :aria-controls="controlId" @mousedown.prevent @click="clearFromControl"><slot name="clear-icon"><AppIcon name="close" :size="12"/></slot></button>
    <Teleport to="body" :disabled="!appendToBody"><Transition name="select-portal"><div v-if="resolvedOpen" v-bind="portalThemeAttrs" class="ui-cascader-portal" :style="portalThemeStyle" :role="appendToBody?'region':undefined" :aria-label="appendToBody?`${resolvedAriaLabel||resolvedPlaceholder} popup`:undefined" @focusin="handleFocusIn" @focusout="handleFocusOut" @keydown="onKeydown">
      <div ref="panelRef" class="ui-cascader-menu" :class="{'ui-floating-panel':appendToBody}" :style="panelStyle" :data-placement="appendToBody?actualPlacement:(dropUp?'top-start':'bottom-start')" :dir="direction" :aria-busy="loading||undefined">
        <label v-if="searchable" class="ui-cascader-search"><slot name="search-prefix"><AppIcon name="search" :size="14"/></slot><input ref="searchInputRef" :value="query" type="search" autocomplete="off" :placeholder="resolvedSearchPlaceholder" :aria-label="resolvedSearchPlaceholder" :aria-controls="menuId" :aria-activedescendant="activeDescendant" @input="onSearchInput" @compositionstart="composing=true" @compositionend="onCompositionEnd" @keydown.stop="onKeydown"/></label>
        <div v-if="loading" class="ui-select-state ui-cascader-loading-state" role="status" aria-live="polite"><slot name="loading"><span class="spinner ui-cascader-spinner"/><span>{{ resolvedLoadingText }}</span></slot></div>
        <div v-else-if="searchMode" :id="menuId" class="ui-cascader-results" role="listbox" :aria-label="resolvedAriaLabel||resolvedPlaceholder" :aria-multiselectable="multiple||undefined"><button v-for="(record,index) in searchResults" :id="optionId('search',index)" :key="record.key" type="button" role="option" tabindex="-1" :class="{active:index===activeIndex,selected:isSelected(record)}" :aria-selected="isSelected(record)" :disabled="record.disabled" @pointerdown.prevent @mouseenter="!record.disabled&&(activeIndex=index)" @click="toggleRecord(record,'search',$event)"><span v-if="multiple" class="ui-cascader-check" :class="{checked:checkState(record).checked,indeterminate:checkState(record).indeterminate}" aria-hidden="true"><AppIcon v-if="checkState(record).checked" name="check" :size="11"/></span><slot name="option-icon" :node="publicNode(record)"><AppIcon v-if="record.icon" :name="record.icon" :size="14"/></slot><slot name="option" :node="publicNode(record)" :selected="isSelected(record)" :active="index===activeIndex"><span class="ui-cascader-option-copy"><span>{{ formatLabel(record) }}</span><small v-if="record.description">{{ record.description }}</small></span></slot></button><div v-if="!searchResults.length" class="ui-select-state ui-cascader-empty" role="status"><slot name="empty" :query="query"><AppIcon name="search" :size="18"/><span>{{ resolvedEmptyText }}</span></slot></div></div>
        <div v-else-if="treeModel.roots.length" :id="menuId" class="ui-cascader-columns" :aria-label="resolvedAriaLabel||resolvedPlaceholder"><div v-for="(options,columnIndex) in columns" :key="columnIndex" class="ui-cascader-column" role="listbox" :aria-label="t('cascader.level',{level:columnIndex+1})" :aria-multiselectable="multiple||undefined"><button v-for="(record,index) in options" :id="optionId(columnIndex,index)" :key="record.key" type="button" role="option" tabindex="-1" :class="{active:columnIndex===activeColumn&&index===activeIndex,selected:multiple?checkState(record).checked:isSelected(record),loading:isLoading(record),error:loadErrors.has(record.key)}" :aria-selected="multiple?checkState(record).checked:isSelected(record)" :aria-disabled="record.disabled||undefined" :disabled="record.disabled" @pointerdown.prevent @mouseenter="onOptionEnter(record,columnIndex)" @click="activateRecord(record,columnIndex,'pointer',$event,{selectBranch:true})"><span v-if="multiple" class="ui-cascader-check" :class="{checked:checkState(record).checked,indeterminate:checkState(record).indeterminate}" aria-hidden="true" @click.stop="toggleRecord(record,'check',$event)"><AppIcon v-if="checkState(record).checked" name="check" :size="11"/></span><slot name="option-icon" :node="publicNode(record)"><AppIcon v-if="record.icon" class="ui-cascader-option-icon" :name="record.icon" :size="14"/></slot><slot name="option" :node="publicNode(record)" :selected="isSelected(record)" :active="columnIndex===activeColumn&&index===activeIndex"><span class="ui-cascader-option-copy"><span>{{ record.label }}</span><small v-if="record.description">{{ record.description }}</small></span></slot><span class="ui-cascader-option-action"><span v-if="isLoading(record)" class="spinner ui-cascader-node-spinner"/><span v-else-if="loadErrors.has(record.key)" class="ui-cascader-retry" role="img" :title="resolvedErrorText" :aria-label="t('cascader.retryNode',{label:record.label})"><slot name="error" :error="loadErrors.get(record.key)" :node="publicNode(record)"><AppIcon name="refresh" :size="12"/></slot></span><AppIcon v-else-if="record.branch" class="ui-directional-icon" name="chevronRight" :size="12"/></span></button></div></div>
        <div v-else class="ui-select-state ui-cascader-empty" role="status"><slot name="empty" :query="query"><AppIcon name="inbox" :size="18"/><span>{{ resolvedEmptyText }}</span></slot></div><div v-if="$slots.footer" class="ui-select-footer"><slot name="footer" :query="query" :options="searchMode?searchResults.map(publicNode):activeOptions.map(publicNode)" :value="resolvedValue" :active-path="resolvedActivePath"/></div>
      </div>
    </div></Transition></Teleport>
  </div>
</template>
