import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const root=resolve(import.meta.dirname,'..')
const manifest=JSON.parse(readFileSync(resolve(root,'api-manifest.json'),'utf8'))
const write=process.argv.includes('--write')

const categoryDefinitions=[
  {id:'foundations',label:'基础与布局',description:'全局配置、图标、栅格、布局、间距、分隔与可调整分栏。',components:['UiConfigProvider','UiIcon','UiLayout','UiGrid','UiCol','UiSpace','UiDivider','UiSplitter']},
  {id:'actions',label:'操作',description:'触发主要任务和悬浮快捷操作。',components:['UiButton','UiFloatButton']},
  {id:'forms',label:'数据录入',description:'输入、选择、日期时间、条件编排、表单编排和文件上传。',components:['UiAutoComplete','UiCascader','UiCheckbox','UiColorPicker','UiDatePicker','UiDateRangePicker','UiForm','UiFormItem','UiFormList','UiSchemaForm','UiInput','UiInputTag','UiMentions','UiMultiSelect','UiNumberInput','UiOtpInput','UiQueryBuilder','UiRadio','UiRate','UiSegmented','UiSelect','UiSlider','UiSwitch','UiTextarea','UiTimePicker','UiTimeRangePicker','UiTransfer','UiTreeSelect','UiUpload']},
  {id:'data',label:'数据展示',description:'结构化内容、媒体、轮播、状态、文本、列表、表格和虚拟数据。',components:['UiAvatar','UiBadge','UiCalendar','UiCard','UiCarousel','UiCollapse','UiDataGrid','UiDescriptions','UiImage','UiList','UiListToolbar','UiStatistic','UiTable','UiTag','UiTimeline','UiTree','UiTypography','UiVirtualList','UiWatermark']},
  {id:'navigation',label:'导航',description:'吸顶操作、锚点、层级、菜单、分页、步骤、页签和快捷检索。',components:['UiAffix','UiAnchor','UiBreadcrumb','UiCommandPalette','UiDropdown','UiMenu','UiPagination','UiSteps','UiTabs']},
  {id:'feedback',label:'反馈与浮层',description:'提示、加载、空状态、结果和模态浮层。',components:['UiAlert','UiDrawer','UiEmpty','UiModal','UiNotification','UiPopconfirm','UiPopover','UiProgress','UiResult','UiSkeleton','UiSpin','UiStatusPage','UiToastHost','UiTooltip','UiTour']},
]

const assigned=new Map()
for(const category of categoryDefinitions){
  for(const name of category.components){
    if(assigned.has(name))throw new Error(`Duplicate API documentation category: ${name}`)
    assigned.set(name,category)
  }
}
const publicNames=manifest.components.map(component=>component.name)
const missing=publicNames.filter(name=>!assigned.has(name))
const unknown=[...assigned.keys()].filter(name=>!publicNames.includes(name))
if(missing.length||unknown.length)throw new Error(`API documentation category coverage failed: missing=${missing.join(',')||'-'} unknown=${unknown.join(',')||'-'}`)
if(manifest.schemaVersion!==3)throw new Error(`API documentation requires api-manifest schema 3; received ${manifest.schemaVersion}`)

const components=manifest.components.map(component=>{
  const category=assigned.get(component.name)
  return {
    name:component.name,
    category:category.id,
    categoryLabel:category.label,
    subpath:component.subpath,
    imports:component.imports,
    propsType:component.propsType,
    props:component.propDetails,
    emitsType:component.emitsType,
    emits:component.emitDetails,
    slotsType:component.slotsType,
    slots:component.slotDetails,
  }
})
const categories=categoryDefinitions.map(({components:names,...category})=>({...category,count:names.length}))
const docs={
  schemaVersion:1,
  package:manifest.package,
  version:manifest.version,
  generatedFrom:'api-manifest.json',
  categories,
  components,
}
const json=JSON.stringify(docs,null,2)+'\n'

const escapeCell=value=>String(value??'—').replaceAll('|','\\|').replaceAll('\n',' ')
const lines=[
  '# Lan UI Component API',
  '',
  `> Generated from \`api-manifest.json\` schema ${manifest.schemaVersion} for \`${manifest.package}@${manifest.version}\`. Do not edit this file directly.`,
  '',
  `- Components: **${components.length}**`,
  `- Categories: **${categories.length}**`,
  `- Props: **${components.reduce((sum,item)=>sum+item.props.length,0)}**`,
  `- Events: **${components.reduce((sum,item)=>sum+item.emits.length,0)}**`,
  `- Slots: **${components.reduce((sum,item)=>sum+item.slots.length,0)}**`,
  '',
]
for(const category of categories){
  lines.push(`## ${category.label}`,'',category.description,'')
  for(const component of components.filter(item=>item.category===category.id)){
    lines.push(`### ${component.name}`,'','```ts',component.imports.root,component.imports.subpath,'```','')
    lines.push(`#### Props · \`${component.propsType}\``,'','| Name | Required | Type | Default | Runtime |','| --- | --- | --- | --- | --- |')
    if(component.props.length)for(const prop of component.props)lines.push(`| \`${escapeCell(prop.name)}\` | ${prop.required?'yes':'no'} | \`${escapeCell(prop.type)}\` | \`${escapeCell(prop.default?.value)}\` | ${escapeCell(prop.runtimeTypes.join(' / '))} |`)
    else lines.push('| — | — | — | — | — |')
    lines.push('',`#### Events · \`${component.emitsType}\``,'','| Name | Signature |','| --- | --- |')
    if(component.emits.length)for(const event of component.emits)lines.push(`| \`${escapeCell(event.name)}\` | \`${escapeCell(event.type)}\` |`)
    else lines.push('| — | — |')
    lines.push('',`#### Slots · \`${component.slotsType}\``,'','| Name | Required | Signature |','| --- | --- | --- |')
    if(component.slots.length)for(const slot of component.slots)lines.push(`| \`${escapeCell(slot.name)}\` | ${slot.required?'yes':'no'} | \`${escapeCell(slot.type)}\` |`)
    else lines.push('| — | — | — |')
    lines.push('')
  }
}
const markdown=lines.join('\n').replace(/\n+$/,'')+'\n'
const targets=[
  [resolve(root,'src/generated/component-api.json'),json],
  [resolve(root,'public/component-api.json'),json],
  [resolve(root,'COMPONENT-API.md'),markdown],
]
const totals={props:components.reduce((sum,item)=>sum+item.props.length,0),emits:components.reduce((sum,item)=>sum+item.emits.length,0),slots:components.reduce((sum,item)=>sum+item.slots.length,0)}
if(write){
  for(const [target,content] of targets){mkdirSync(dirname(target),{recursive:true});writeFileSync(target,content,'utf8')}
  console.log(`API_DOCS WRITE components=${components.length} categories=${categories.length} props=${totals.props} emits=${totals.emits} slots=${totals.slots} outputs=${targets.length}`)
}else{
  const drift=targets.filter(([target,content])=>{try{return readFileSync(target,'utf8').replace(/\r\n?/g,'\n')!==content}catch{return true}}).map(([target])=>target)
  if(drift.length){console.error(`API_DOCS FAIL generated output differs: ${drift.map(target=>target.replace(`${root}\\`,'' )).join(', ')}; run pnpm run api:generate`);process.exit(1)}
  console.log(`API_DOCS PASS components=${components.length} categories=${categories.length} props=${totals.props} emits=${totals.emits} slots=${totals.slots} drift=0`)
}
